# App Engine configuration - Versión optimizada
# Usa requirements-production.txt en lugar de requirements.txt

runtime: python311
instance_class: F2

env_variables:
  FLASK_ENV: production
  SECRETS_PROVIDER: "gcp"
  GOOGLE_CLOUD_PROJECT: "mantenimiento-470311"
  DB_TYPE: postgresql
  DB_USER: gmao-user
  DB_NAME: gmao
  # Actualizado para el proyecto "Mantenimiento" (disfood)
  DB_HOST: "/cloudsql/mantenimiento-470311:europe-west1:gmao-postgres"
  SERVER_URL: https://mantenimiento-470311.ew.r.appspot.com
  # Cloud Storage bucket para persistencia de archivos
  GCS_BUCKET_NAME: "gmao-mantenimiento-201193253693"
  # Configuración de email (Gmail/Google Workspace)
  MAIL_SERVER: smtp.gmail.com
  MAIL_PORT: "587"
  MAIL_USE_TLS: "True"
  MAIL_USERNAME: j_hidalgo@disfood.com
  # MAIL_PASSWORD se obtiene vía Secret Manager en runtime
  MAIL_PASSWORD: ""
  ADMIN_EMAILS: j_hidalgo@disfood.com

beta_settings:
  cloud_sql_instances: mantenimiento-470311:europe-west1:gmao-postgres

# Instalación optimizada usando requirements-production.txt
handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /favicon.svg
  static_files: static/favicon.svg
  upload: static/favicon.svg
- url: /.*
  script: auto

# Usa gunicorn con timeout extendido
entrypoint: gunicorn -b :$PORT -w 4 --timeout 300 run:app

# Health checks
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Recursos optimizados
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
