"""Aumentar precisión de cantidades en lotes a 4 decimales

Revision ID: 45e9b366f706
Revises: a4fe67ffab43
Create Date: 2025-10-14 17:40:43.076199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e9b366f706'
down_revision = 'a4fe67ffab43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_inventario', schema=None) as batch_op:
        batch_op.alter_column('cantidad_inicial',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
        batch_op.alter_column('cantidad_actual',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=False)
        batch_op.alter_column('cantidad_reservada',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_inventario', schema=None) as batch_op:
        batch_op.alter_column('cantidad_reservada',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('cantidad_actual',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('cantidad_inicial',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
