"""Agregar relación orden-plan de mantenimiento

Revision ID: 499968d1e362
Revises:
Create Date: 2025-10-02 15:44:22.910069

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "499968d1e362"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orden_trabajo", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plan_mantenimiento_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_orden_plan_mantenimiento",
            "plan_mantenimiento",
            ["plan_mantenimiento_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orden_trabajo", schema=None) as batch_op:
        batch_op.drop_constraint("fk_orden_plan_mantenimiento", type_="foreignkey")
        batch_op.drop_column("plan_mantenimiento_id")

    # ### end Alembic commands ###
