"""Añadir tabla tarea_solicitud para checklist de tareas

Revision ID: 563b0d31a3fc
Revises: 721658648421
Create Date: 2025-10-19 14:08:03.943789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563b0d31a3fc'
down_revision = '721658648421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.Column('completada_por', sa.String(length=100), nullable=True),
    sa.Column('completada_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completada_por_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_inventario_activo'))
        batch_op.drop_index(batch_op.f('idx_inventario_activo_categoria'))
        batch_op.drop_index(batch_op.f('idx_inventario_categoria_ilike'), postgresql_ops={'lower(categoria::text)': 'text_pattern_ops'})
        batch_op.drop_index(batch_op.f('idx_inventario_codigo_ilike'), postgresql_ops={'lower(codigo::text)': 'text_pattern_ops'})
        batch_op.drop_index(batch_op.f('idx_inventario_codigo_sort'))
        batch_op.drop_index(batch_op.f('idx_inventario_descripcion_ilike'), postgresql_ops={'lower(descripcion::text)': 'text_pattern_ops'})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inventario_descripcion_ilike'), [sa.literal_column('lower(descripcion::text)')], unique=False, postgresql_ops={'lower(descripcion::text)': 'text_pattern_ops'})
        batch_op.create_index(batch_op.f('idx_inventario_codigo_sort'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventario_codigo_ilike'), [sa.literal_column('lower(codigo::text)')], unique=False, postgresql_ops={'lower(codigo::text)': 'text_pattern_ops'})
        batch_op.create_index(batch_op.f('idx_inventario_categoria_ilike'), [sa.literal_column('lower(categoria::text)')], unique=False, postgresql_ops={'lower(categoria::text)': 'text_pattern_ops'})
        batch_op.create_index(batch_op.f('idx_inventario_activo_categoria'), ['activo', 'categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventario_activo'), ['activo'], unique=False)

    op.drop_table('tarea_solicitud')
    # ### end Alembic commands ###
