"""Crear sistema FIFO

Revision ID: 69fb2271b36e
Revises: 61af0baf2d34
Create Date: 2025-10-12 10:07:21.454764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fb2271b36e'
down_revision = '61af0baf2d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_entrada', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('cantidad_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_reservada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('documento_origen', sa.String(length=50), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_entrada_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_creacion', sa.String(length=50), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_modificacion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ),
    sa.ForeignKeyConstraint(['movimiento_entrada_id'], ['movimiento_inventario.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_inventario_id', sa.Integer(), nullable=True),
    sa.Column('orden_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('documento_referencia', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_inventario.id'], ),
    sa.ForeignKeyConstraint(['movimiento_inventario_id'], ['movimiento_inventario.id'], ),
    sa.ForeignKeyConstraint(['orden_trabajo_id'], ['orden_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento_lote')
    op.drop_table('lote_inventario')
    # ### end Alembic commands ###
