"""Actualizar modelo Proveedor según columnas de Excel

Revision ID: 6c136aef235c
Revises: fe45ab8fab8c
Create Date: 2025-10-14 17:56:15.095989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c136aef235c'
down_revision = 'fe45ab8fab8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('nif',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cuenta_contable',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_column('activo')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('cuenta_contable',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('nif',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
