"""Agregar fecha_movimiento a MovimientoLote

Revision ID: fe45ab8fab8c
Revises: 45e9b366f706
Create Date: 2025-10-14 17:43:41.079596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe45ab8fab8c'
down_revision = '45e9b366f706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_lote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_movimiento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento_lote', schema=None) as batch_op:
        batch_op.drop_column('fecha_movimiento')

    # ### end Alembic commands ###
